// ===== PRODUCTS DATA – NhàThuốc+ =====
const PRODUCTS_DATA = {
  // =====================
  // FLASH SALE – id 1–10
  // =====================
  1: {
    id: 1,
    name: 'Vitamin C 500mg – Hộp 100 viên',
    ingredient: 'Ascorbic Acid',
    desc: 'Bổ sung Vitamin C giúp tăng cường sức đề kháng, hỗ trợ chống oxy hóa và làm đẹp da. Phù hợp cho người hay mệt mỏi, thiếu chất.',
    price: 145000, originalPrice: 180000, discount: 19,
    rating: 4.7, ratingCount: 312,
    unit: '/hộp', expiry: '06/2027',
    imgs: [
      '../image/C.webp',
      '../image/C.webp',
      '../image/C.webp',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Vitamin C',
    tabs: {
      congdung: {
        text: 'Vitamin C 500mg là viên uống bổ sung Ascorbic Acid giúp tăng cường miễn dịch và chống oxy hóa.',
        list: ['Tăng cường hệ miễn dịch, phòng ngừa cảm cúm', 'Hỗ trợ tổng hợp collagen, làm đẹp da', 'Chống oxy hóa, bảo vệ tế bào', 'Tăng hấp thu sắt từ thực phẩm'],
        warning: 'Dùng quá liều Vitamin C có thể gây tiêu chảy, buồn nôn. Không dùng quá 1000mg/ngày.',
      },
      lieudung: 'Người lớn: 1–2 viên/ngày sau bữa ăn. Trẻ em trên 12 tuổi: 1 viên/ngày. Uống cùng nhiều nước.',
      thanhphan: 'Mỗi viên chứa: Ascorbic Acid (Vitamin C) 500mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Không dùng cho người mẫn cảm với Vitamin C, người bị sỏi thận oxalate, người mắc bệnh thalassemia.',
    },
  },
  2: {
    id: 2,
    name: 'Paracetamol 500mg – Hộp 20 viên',
    ingredient: 'Paracetamol',
    desc: 'Thuốc giảm đau, hạ sốt phổ biến và an toàn. Hiệu quả với đau đầu, đau răng, đau cơ, và hạ sốt trong các trường hợp cảm cúm, cảm lạnh.',
    price: 25000, originalPrice: 35000, discount: 29,
    rating: 4.5, ratingCount: 248,
    unit: '/hộp', expiry: '12/2026',
    imgs: [
      '../image/P.png',
      '../image/P.png',
      '../image/P.png',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Giảm đau, Hạ sốt',
    tabs: {
      congdung: {
        text: 'Paracetamol 500mg là thuốc giảm đau, hạ sốt được sử dụng rộng rãi và an toàn cho cả người lớn và trẻ em.',
        list: ['Giảm đau nhẹ và vừa: đau đầu, đau răng, đau cơ, đau khớp', 'Hạ sốt trong các trường hợp cảm cúm, cảm lạnh', 'Giảm đau sau tiêm chủng cho trẻ em', 'Giảm đau kinh nguyệt ở phụ nữ'],
        warning: 'Paracetamol không có tác dụng chống viêm. Nếu triệu chứng kéo dài quá 3 ngày, vui lòng tham khảo ý kiến bác sĩ.',
      },
      lieudung: 'Người lớn và trẻ em trên 12 tuổi: 500mg–1000mg/lần, tối đa 4 lần/ngày (cách nhau ít nhất 4 giờ). Trẻ em 6–12 tuổi: 250mg–500mg/lần.',
      thanhphan: 'Mỗi viên nén chứa: Paracetamol 500mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Chống chỉ định với người mẫn cảm với Paracetamol, bệnh nhân suy gan nặng, hoặc uống rượu bia nhiều. Không dùng cùng các thuốc khác có chứa Paracetamol.',
    },
  },
  3: {
    id: 3,
    name: 'Nhiệt kế điện tử – Đo thân nhiệt chính xác',
    ingredient: 'Thiết bị y tế',
    desc: 'Nhiệt kế điện tử kỹ thuật số đo thân nhiệt nhanh chóng, chính xác trong 60 giây. Dùng được cho cả trẻ em và người lớn.',
    price: 120000, originalPrice: 180000, discount: 33,
    rating: 4.6, ratingCount: 189,
    unit: '/cái', expiry: 'BH 12 tháng',
    imgs: [
      '../image/N.web',
      '../image/N.web',
      '../image/N.web',
    ],
    thumbLabels: ['Sản phẩm', 'Hộp', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'Nhiệt kế',
    tabs: {
      congdung: {
        text: 'Nhiệt kế điện tử cho kết quả đo thân nhiệt nhanh và chính xác, phù hợp sử dụng tại nhà.',
        list: ['Đo thân nhiệt qua miệng, nách hoặc hậu môn', 'Kết quả hiển thị sau 60 giây', 'Cảnh báo sốt bằng âm thanh khi nhiệt độ trên 38°C', 'Bộ nhớ lưu kết quả đo lần cuối'],
        warning: 'Vệ sinh đầu đo sau mỗi lần sử dụng. Không đo ngay sau khi ăn, uống hoặc vận động mạnh.',
      },
      lieudung: 'Đặt đầu đo vào nách hoặc miệng. Nhấn nút Start và giữ yên đến khi có tiếng bíp. Đọc kết quả trên màn hình LCD.',
      thanhphan: 'Cảm biến nhiệt độ điện tử, màn hình LCD, pin LR41 (kèm theo), bao đựng.',
      chongchidinh: 'Không dùng khi thiết bị bị hỏng, nứt vỡ. Không ngâm nước.',
    },
  },
  4: {
    id: 4,
    name: 'Kem dưỡng da – Niacinamide + Hyaluronic Acid',
    ingredient: 'Niacinamide + Hyaluronic Acid',
    desc: 'Kem dưỡng ẩm cao cấp kết hợp Niacinamide và Hyaluronic Acid giúp dưỡng ẩm sâu, làm mờ vết thâm và cải thiện kết cấu da.',
    price: 320000, originalPrice: 450000, discount: 29,
    rating: 4.8, ratingCount: 425,
    unit: '/tuýp 50ml', expiry: '03/2027',
    imgs: [
      '../image/K.webp',
      '../image/K.webp',
      '../image/K.webp',
    ],
    thumbLabels: ['Sản phẩm', 'Texture', 'Thành phần'],
    cat: 'Chăm sóc cá nhân', catLink: 'search.html?cat=cham-soc-ca-nhan', catSub: 'Dưỡng da mặt',
    tabs: {
      congdung: {
        text: 'Kem dưỡng ẩm chuyên sâu với công thức kết hợp Niacinamide 5% và Hyaluronic Acid 2%.',
        list: ['Dưỡng ẩm sâu, giữ ẩm cho da suốt 24 giờ', 'Làm mờ vết thâm, đốm nâu và tàn nhang', 'Cải thiện kết cấu da, làm da mịn màng', 'Phù hợp mọi loại da kể cả da nhạy cảm'],
        warning: 'Tránh tiếp xúc với mắt. Ngừng sử dụng nếu kích ứng. Bôi kem chống nắng khi ra ngoài.',
      },
      lieudung: 'Lấy lượng kem vừa đủ, thoa đều lên mặt và cổ sau khi rửa sạch. Dùng sáng và tối. Tránh vùng mắt.',
      thanhphan: 'Niacinamide 5%, Hyaluronic Acid 2%, Glycerin, Cetearyl Alcohol, nước tinh khiết và các tá dược.',
      chongchidinh: 'Không dùng cho da đang bị viêm nhiễm nặng. Test thử trên vùng da nhỏ trước khi dùng toàn mặt.',
    },
  },
  5: {
    id: 5,
    name: 'Sữa bột Aptamil – Dinh dưỡng cho trẻ 0–12 tháng',
    ingredient: 'Aptamil Stage 1',
    desc: 'Sữa bột Aptamil Stage 1 được thiết kế đặc biệt cho trẻ từ 0–12 tháng tuổi với công thức gần giống sữa mẹ, bổ sung DHA, ARA và Prebiotics.',
    price: 580000, originalPrice: 650000, discount: 11,
    rating: 4.9, ratingCount: 567,
    unit: '/hộp 800g', expiry: '09/2026',
    imgs: [
      '../image/S.jp',
      '../image/S.jp',
      '../image/S.jp',
    ],
    thumbLabels: ['Hộp', 'Nhãn', 'Chi tiết'],
    cat: 'Mẹ & Bé', catLink: 'search.html?cat=me-be', catSub: 'Sữa bột trẻ em',
    tabs: {
      congdung: {
        text: 'Aptamil Stage 1 cung cấp dinh dưỡng toàn diện cho trẻ sơ sinh từ 0–12 tháng tuổi.',
        list: ['Bổ sung DHA & ARA hỗ trợ phát triển não bộ và thị lực', 'Prebiotics GOS/FOS hỗ trợ hệ tiêu hóa', 'Protein whey dễ tiêu hóa', 'Đầy đủ vitamin và khoáng chất cần thiết'],
        warning: 'Sữa mẹ là nguồn dinh dưỡng tốt nhất cho trẻ sơ sinh. Chỉ dùng sữa công thức khi không thể cho con bú.',
      },
      lieudung: 'Pha 1 muỗng gạt ngang (4.4g) với 30ml nước đã đun sôi để nguội. Cho trẻ uống ngay sau khi pha.',
      thanhphan: 'Lactose, dầu thực vật, protein whey, DHA, ARA, GOS/FOS, Vitamin A, B, C, D, E và khoáng chất.',
      chongchidinh: 'Không dùng cho trẻ bị dị ứng với protein sữa bò. Tham khảo ý kiến bác sĩ trước khi dùng.',
    },
  },
  6: {
    id: 6,
    name: 'Omega-3 Fish Oil – EPA + DHA 1000mg',
    ingredient: 'EPA + DHA 1000mg',
    desc: 'Viên dầu cá Omega-3 hàm lượng cao, bổ sung EPA và DHA giúp bảo vệ tim mạch, tăng cường trí nhớ và hỗ trợ chức năng não bộ.',
    price: 210000, originalPrice: 280000, discount: 25,
    rating: 4.6, ratingCount: 203,
    unit: '/hộp 60 viên', expiry: '08/2026',
    imgs: [
      '../image/o.png',
      '../image/o.png',
      '../image/o.png',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Omega-3',
    tabs: {
      congdung: {
        text: 'Omega-3 Fish Oil cung cấp EPA 300mg và DHA 200mg từ dầu cá tự nhiên, hỗ trợ sức khỏe toàn diện.',
        list: ['Bảo vệ tim mạch, giảm triglyceride trong máu', 'Tăng cường trí nhớ và chức năng não bộ', 'Hỗ trợ sức khỏe mắt và giảm khô mắt', 'Chống viêm, hỗ trợ xương khớp'],
        warning: 'Tham khảo ý kiến bác sĩ nếu đang dùng thuốc chống đông máu. Không dùng khi dị ứng cá.',
      },
      lieudung: 'Người lớn: 1–2 viên/ngày trong bữa ăn. Uống với nhiều nước. Không nhai viên nang.',
      thanhphan: 'Dầu cá tự nhiên 1000mg (EPA 300mg, DHA 200mg), Vitamin E, vỏ nang gelatin.',
      chongchidinh: 'Không dùng cho người dị ứng hải sản, người đang dùng thuốc chống đông máu Warfarin.',
    },
  },
  7: {
    id: 7,
    name: 'Khẩu trang y tế 4D – Hộp 10 cái kháng khuẩn',
    ingredient: 'Khẩu trang kháng khuẩn 4 lớp',
    desc: 'Khẩu trang y tế 4D kháng khuẩn, lọc bụi mịn PM2.5, thiết kế 4 lớp bảo vệ tối ưu. Phù hợp cho môi trường bệnh viện và đời sống hàng ngày.',
    price: 30000, originalPrice: 50000, discount: 40,
    rating: 4.4, ratingCount: 156,
    unit: '/hộp 10 cái', expiry: '12/2027',
    imgs: [
      '../image/1.webp',
      '../image/1.webp',
      '../image/1.webp',
    ],
    thumbLabels: ['Hộp', 'Cái', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'Khẩu trang',
    tabs: {
      congdung: {
        text: 'Khẩu trang y tế 4D với cấu trúc 4 lớp lọc hiệu quả, bảo vệ người đeo khỏi vi khuẩn, virus và bụi mịn.',
        list: ['Lọc bụi mịn PM2.5 hiệu quả trên 95%', 'Kháng khuẩn, ngăn vi rút lây lan', 'Thiết kế 4D ôm khít mặt, không bí thở', 'Phù hợp dùng trong y tế và đời thường'],
        warning: 'Mỗi khẩu trang chỉ dùng 1 lần. Thay khẩu trang khi bị ẩm hoặc sau 4–8 giờ sử dụng.',
      },
      lieudung: 'Đeo đúng chiều (mặt màu ra ngoài). Che kín mũi và miệng. Không chạm tay vào mặt trong khẩu trang.',
      thanhphan: '4 lớp: lớp vải không dệt PP ngoài, lớp lọc meltblown, lớp hấp thụ ẩm, lớp vải mềm tiếp xúc da.',
      chongchidinh: 'Không dùng lại khẩu trang đã qua sử dụng. Không dùng cho trẻ em dưới 2 tuổi.',
    },
  },
  8: {
    id: 8,
    name: 'Gel rửa tay khô – Cồn 70% kháng khuẩn',
    ingredient: 'Ethanol 70%',
    desc: 'Gel rửa tay khô với cồn 70% diệt khuẩn nhanh không cần nước, tiện lợi mang theo mọi nơi. Bổ sung dưỡng ẩm giúp tay mềm mịn sau khi dùng.',
    price: 48000, originalPrice: 60000, discount: 20,
    rating: 4.5, ratingCount: 334,
    unit: '/chai 100ml', expiry: '06/2026',
    imgs: [
      '../image/g.webp',
      '../image/g.webp',
      '../image/g.webp',
    ],
    thumbLabels: ['Chai', 'Kết cấu', 'Nhãn'],
    cat: 'Chăm sóc cá nhân', catLink: 'search.html?cat=cham-soc-ca-nhan', catSub: 'Vệ sinh tay',
    tabs: {
      congdung: {
        text: 'Gel rửa tay khô với cồn Ethanol 70% tiêu diệt 99.9% vi khuẩn và virus trong vòng 30 giây.',
        list: ['Diệt 99.9% vi khuẩn, virus gây bệnh', 'Không cần nước, tiện lợi mọi lúc mọi nơi', 'Có dưỡng ẩm Glycerin giữ tay mềm mịn', 'Mùi thơm nhẹ, khô nhanh không dính tay'],
        warning: 'Tránh xa mắt và trẻ em. Không nuốt. Tránh xa lửa khi đang dùng.',
      },
      lieudung: 'Bơm 2–3ml vào lòng bàn tay. Xoa đều khắp tay trong 30 giây đến khi khô hoàn toàn.',
      thanhphan: 'Ethanol 70%, Glycerin, Carbomer, Triethanolamine, nước tinh khiết, hương liệu.',
      chongchidinh: 'Không dùng cho trẻ em dưới 3 tuổi. Không dùng trên vết thương hở.',
    },
  },
  9: {
    id: 9,
    name: 'Vitamin D3 2000IU – Hộp 60 viên',
    ingredient: 'Cholecalciferol',
    desc: 'Vitamin D3 2000IU bổ sung Cholecalciferol giúp xương chắc khỏe, tăng hấp thu Canxi, hỗ trợ hệ miễn dịch và sức khỏe tim mạch.',
    price: 175000, originalPrice: 225000, discount: 22,
    rating: 4.7, ratingCount: 278,
    unit: '/hộp 60 viên', expiry: '11/2026',
    imgs: [
      '../image/v.jpg',
      '../image/v.jpg',
      '../image/v.jpg',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Vitamin D',
    tabs: {
      congdung: {
        text: 'Vitamin D3 2000IU cung cấp Cholecalciferol thiết yếu cho sức khỏe xương và miễn dịch.',
        list: ['Tăng hấp thu Canxi và Phospho, giúp xương chắc khỏe', 'Hỗ trợ hệ miễn dịch, giảm nguy cơ nhiễm trùng', 'Hỗ trợ sức khỏe tim mạch và điều hòa huyết áp', 'Giảm nguy cơ loãng xương ở người cao tuổi'],
        warning: 'Không dùng quá liều khuyến cáo. Tham khảo bác sĩ nếu đang điều trị bệnh thận hoặc tăng canxi máu.',
      },
      lieudung: 'Người lớn: 1 viên/ngày sau bữa ăn có chất béo để tăng hấp thu. Trẻ em: theo chỉ định bác sĩ.',
      thanhphan: 'Mỗi viên chứa: Cholecalciferol (Vitamin D3) 2000IU (50mcg). Dầu hướng dương, gelatin, glycerin.',
      chongchidinh: 'Không dùng khi tăng canxi máu, tăng vitamin D, sỏi thận. Thận trọng với người suy thận.',
    },
  },
  10: {
    id: 10,
    name: 'Thuốc ho Bảo Thanh – Siro cao lá thường xuân',
    ingredient: 'Cao lá thường xuân (Hedera helix)',
    desc: 'Thuốc ho thảo dược từ cao lá thường xuân giúp long đờm, giảm ho nhanh hiệu quả. An toàn cho cả trẻ em từ 2 tuổi và người lớn.',
    price: 85000, originalPrice: 100000, discount: 15,
    rating: 4.6, ratingCount: 412,
    unit: '/chai 100ml', expiry: '05/2026',
    imgs: [
      '../image/t.jpg',
      '../image/t.jpg',
      '../image/t.jpg',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Thuốc ho',
    tabs: {
      congdung: {
        text: 'Thuốc ho Bảo Thanh chiết xuất từ cao lá thường xuân (Hedera helix) giúp giảm ho và long đờm hiệu quả.',
        list: ['Long đờm, giúp đờm dễ tống ra ngoài', 'Giảm ho khan, ho có đờm do viêm phế quản', 'Giãn phế quản, hỗ trợ hô hấp dễ dàng hơn', 'Thảo dược tự nhiên, an toàn cho trẻ từ 2 tuổi'],
        warning: 'Không dùng cho trẻ dưới 2 tuổi. Nếu ho kéo dài trên 7 ngày hoặc kèm sốt cao, cần gặp bác sĩ.',
      },
      lieudung: 'Trẻ 2–5 tuổi: 2.5ml x 3 lần/ngày. Trẻ 6–12 tuổi: 5ml x 3 lần/ngày. Người lớn: 7.5ml x 3 lần/ngày.',
      thanhphan: 'Cao lá thường xuân (Hedera helix) tương đương 420mg lá khô/5ml, Ethanol, Glycerin, nước tinh khiết.',
      chongchidinh: 'Không dùng cho trẻ dưới 2 tuổi. Không dùng khi dị ứng với thực vật họ Araliaceae.',
    },
  },

  // =====================
  // DANH MỤC – id 50–75
  // =====================

  // --- Thuốc không kê đơn (50–57) ---
  50: {
    id: 50,
    name: 'Paracetamol 500mg',
    ingredient: 'Paracetamol',
    desc: 'Thuốc giảm đau, hạ sốt phổ biến và an toàn. Hiệu quả với đau đầu, đau răng, đau cơ và hạ sốt.',
    price: 25000, originalPrice: 30000, discount: 17,
    rating: 4.5, ratingCount: 520,
    unit: '/hộp', expiry: '12/2026',
    imgs: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Giảm đau, Hạ sốt',
    tabs: {
      congdung: {
        text: 'Paracetamol 500mg là thuốc giảm đau, hạ sốt được sử dụng rộng rãi, an toàn cho cả người lớn và trẻ em.',
        list: ['Giảm đau nhẹ và vừa: đau đầu, đau răng, đau cơ', 'Hạ sốt trong cảm cúm, cảm lạnh', 'Giảm đau sau tiêm chủng', 'Giảm đau kinh nguyệt'],
        warning: 'Không dùng quá 4g/ngày. Nếu triệu chứng kéo dài quá 3 ngày, tham khảo bác sĩ.',
      },
      lieudung: 'Người lớn: 500–1000mg/lần, tối đa 4 lần/ngày. Trẻ 6–12 tuổi: 250–500mg/lần.',
      thanhphan: 'Paracetamol 500mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Mẫn cảm với Paracetamol, suy gan nặng, uống rượu bia nhiều.',
    },
  },
  51: {
    id: 51,
    name: 'Ibuprofen 400mg',
    ingredient: 'Ibuprofen',
    desc: 'Thuốc kháng viêm, giảm đau, hạ sốt nhóm NSAID. Hiệu quả với đau cơ, đau khớp, đau răng và các cơn đau vừa đến nặng.',
    price: 85000, originalPrice: 100000, discount: 15,
    rating: 4.4, ratingCount: 310,
    unit: '/hộp', expiry: '08/2026',
    imgs: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Kháng viêm, Giảm đau',
    tabs: {
      congdung: {
        text: 'Ibuprofen 400mg thuộc nhóm NSAID, có tác dụng kháng viêm, giảm đau và hạ sốt.',
        list: ['Giảm đau cơ, đau khớp, đau lưng', 'Kháng viêm trong viêm khớp, bong gân', 'Hạ sốt hiệu quả', 'Giảm đau răng, đau đầu'],
        warning: 'Uống sau bữa ăn để tránh kích ứng dạ dày. Không dùng cho người loét dạ dày.',
      },
      lieudung: 'Người lớn: 400mg/lần, 3 lần/ngày sau bữa ăn. Không dùng cho trẻ dưới 12 tuổi.',
      thanhphan: 'Ibuprofen 400mg. Tá dược vừa đủ 1 viên bao phim.',
      chongchidinh: 'Loét dạ dày tá tràng, suy thận nặng, phụ nữ mang thai 3 tháng cuối, mẫn cảm NSAID.',
    },
  },
  52: {
    id: 52,
    name: 'Aspirin 100mg',
    ingredient: 'Acetylsalicylic Acid',
    desc: 'Aspirin liều thấp 100mg dùng trong phòng ngừa huyết khối, nhồi máu cơ tim và đột quỵ theo chỉ định bác sĩ.',
    price: 65000, originalPrice: 80000, discount: 19,
    rating: 4.3, ratingCount: 198,
    unit: '/hộp', expiry: '10/2026',
    imgs: [
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Tim mạch',
    tabs: {
      congdung: {
        text: 'Aspirin 100mg liều thấp ức chế kết tập tiểu cầu, dùng trong phòng ngừa các biến cố tim mạch.',
        list: ['Phòng ngừa nhồi máu cơ tim tái phát', 'Phòng ngừa đột quỵ thiếu máu cục bộ', 'Chống kết tập tiểu cầu', 'Dùng lâu dài theo chỉ định bác sĩ'],
        warning: 'Không tự ý dùng Aspirin để phòng ngừa tim mạch mà không có chỉ định bác sĩ.',
      },
      lieudung: 'Người lớn: 1 viên/ngày sau bữa ăn hoặc theo chỉ định bác sĩ.',
      thanhphan: 'Acetylsalicylic Acid 100mg. Tá dược vừa đủ 1 viên bao tan trong ruột.',
      chongchidinh: 'Loét dạ dày, rối loạn đông máu, dị ứng Aspirin, trẻ em dưới 16 tuổi.',
    },
  },
  53: {
    id: 53,
    name: 'Decolgen Forte',
    ingredient: 'Paracetamol + Phenylephrine',
    desc: 'Thuốc điều trị cảm cúm, nghẹt mũi, sổ mũi, đau đầu và hạ sốt. Kết hợp Paracetamol và Phenylephrine cho hiệu quả toàn diện.',
    price: 135000, originalPrice: 160000, discount: 16,
    rating: 4.5, ratingCount: 287,
    unit: '/hộp', expiry: '07/2026',
    imgs: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Cảm cúm',
    tabs: {
      congdung: {
        text: 'Decolgen Forte kết hợp Paracetamol và Phenylephrine điều trị triệu chứng cảm cúm hiệu quả.',
        list: ['Giảm đau đầu, hạ sốt do cảm cúm', 'Thông mũi, giảm nghẹt mũi', 'Giảm sổ mũi, chảy nước mũi', 'Giảm đau họng nhẹ'],
        warning: 'Không dùng cho người cao huyết áp, tim mạch, cường giáp. Không dùng quá 5 ngày.',
      },
      lieudung: 'Người lớn: 1–2 viên/lần, 3–4 lần/ngày. Trẻ 6–12 tuổi: 1 viên/lần, 3 lần/ngày.',
      thanhphan: 'Paracetamol 500mg, Phenylephrine HCl 10mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Cao huyết áp, bệnh tim mạch, cường giáp, phụ nữ mang thai, trẻ dưới 6 tuổi.',
    },
  },
  54: {
    id: 54,
    name: 'Efferalgan 500mg',
    ingredient: 'Paracetamol',
    desc: 'Viên sủi Paracetamol 500mg tan nhanh trong nước, dễ uống, hấp thu nhanh hơn viên thường. Giảm đau, hạ sốt hiệu quả.',
    price: 95000, originalPrice: 115000, discount: 17,
    rating: 4.6, ratingCount: 341,
    unit: '/tuýp 16 viên', expiry: '04/2027',
    imgs: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Tuýp', 'Viên', 'Chi tiết'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Giảm đau, Hạ sốt',
    tabs: {
      congdung: {
        text: 'Efferalgan 500mg dạng viên sủi giúp hấp thu nhanh hơn, phù hợp người khó nuốt viên thường.',
        list: ['Giảm đau đầu, đau răng, đau cơ nhanh chóng', 'Hạ sốt hiệu quả', 'Dạng sủi dễ uống, hấp thu tốt', 'Phù hợp người cao tuổi, người khó nuốt'],
        warning: 'Chứa Natri – thận trọng với người ăn kiêng muối. Không dùng quá 4g Paracetamol/ngày từ mọi nguồn.',
      },
      lieudung: 'Hòa tan 1 viên trong 1 cốc nước (200ml). Người lớn: 1–2 viên/lần, tối đa 4 lần/ngày.',
      thanhphan: 'Paracetamol 500mg, Natri bicarbonate, Acid citric, tá dược sủi vừa đủ.',
      chongchidinh: 'Suy gan nặng, dị ứng Paracetamol, chế độ ăn hạn chế Natri nghiêm ngặt.',
    },
  },
  55: {
    id: 55,
    name: 'Migralgin',
    ingredient: 'Paracetamol + Caffeine',
    desc: 'Thuốc giảm đau đầu, đau nửa đầu kết hợp Paracetamol và Caffeine. Caffeine tăng cường tác dụng giảm đau của Paracetamol.',
    price: 78000, originalPrice: 95000, discount: 18,
    rating: 4.4, ratingCount: 223,
    unit: '/hộp', expiry: '09/2026',
    imgs: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Đau đầu',
    tabs: {
      congdung: {
        text: 'Migralgin kết hợp Paracetamol 500mg và Caffeine 65mg, đặc trị đau đầu và đau nửa đầu.',
        list: ['Đặc trị đau đầu, đau nửa đầu (migraine)', 'Caffeine tăng cường hiệu quả Paracetamol', 'Giảm đau nhanh trong 30 phút', 'Giảm mệt mỏi kèm theo'],
        warning: 'Không dùng cho người nhạy cảm với Caffeine, cao huyết áp, mất ngủ. Không dùng buổi tối.',
      },
      lieudung: 'Người lớn: 1–2 viên/lần khi đau. Không dùng quá 8 viên/ngày.',
      thanhphan: 'Paracetamol 500mg, Caffeine 65mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Mẫn cảm Caffeine, rối loạn lo âu, cao huyết áp không kiểm soát, mang thai.',
    },
  },
  56: {
    id: 56,
    name: 'Thuốc ho Bảo Thanh',
    ingredient: 'Cao lá thường xuân',
    desc: 'Siro thuốc ho thảo dược từ cao lá thường xuân, giúp long đờm và giảm ho hiệu quả, an toàn cho trẻ từ 2 tuổi.',
    price: 85000, originalPrice: 100000, discount: 15,
    rating: 4.6, ratingCount: 412,
    unit: '/chai 100ml', expiry: '05/2026',
    imgs: [
      'https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Thuốc ho',
    tabs: {
      congdung: {
        text: 'Thuốc ho Bảo Thanh chiết xuất từ cao lá thường xuân (Hedera helix) giúp giảm ho và long đờm hiệu quả.',
        list: ['Long đờm, giúp đờm dễ tống ra ngoài', 'Giảm ho khan, ho có đờm', 'Giãn phế quản, hỗ trợ hô hấp', 'An toàn cho trẻ từ 2 tuổi'],
        warning: 'Không dùng cho trẻ dưới 2 tuổi. Ho kéo dài trên 7 ngày cần gặp bác sĩ.',
      },
      lieudung: 'Trẻ 2–5 tuổi: 2.5ml x 3 lần/ngày. Trẻ 6–12 tuổi: 5ml x 3 lần/ngày. Người lớn: 7.5ml x 3 lần/ngày.',
      thanhphan: 'Cao lá thường xuân (Hedera helix) tương đương 420mg lá khô/5ml.',
      chongchidinh: 'Trẻ dưới 2 tuổi. Dị ứng thực vật họ Araliaceae.',
    },
  },
  57: {
    id: 57,
    name: 'Thuốc nhỏ mắt Rohto',
    ingredient: 'Naphazoline HCl',
    desc: 'Thuốc nhỏ mắt Rohto giảm đỏ mắt, ngứa mắt, mỏi mắt do làm việc với màn hình lâu hoặc tiếp xúc khói bụi.',
    price: 49000, originalPrice: 60000, discount: 18,
    rating: 4.5, ratingCount: 389,
    unit: '/lọ 13ml', expiry: '11/2026',
    imgs: [
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Lọ', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc không kê đơn', catLink: 'search.html?cat=thuoc-khong-ke-don', catSub: 'Nhỏ mắt',
    tabs: {
      congdung: {
        text: 'Rohto nhỏ mắt làm dịu và làm sạch mắt, giảm đỏ và mỏi mắt nhanh chóng.',
        list: ['Giảm đỏ mắt do khói bụi, dị ứng', 'Làm dịu mắt mỏi sau thời gian dài dùng màn hình', 'Làm sạch mắt nhẹ nhàng', 'Cảm giác mát lạnh dễ chịu'],
        warning: 'Không dùng quá 4 lần/ngày. Không dùng khi đang đeo kính áp tròng.',
      },
      lieudung: 'Nhỏ 1–2 giọt vào mỗi mắt, tối đa 4 lần/ngày.',
      thanhphan: 'Naphazoline HCl 0.012%, Chlorpheniramine maleate 0.01%, tá dược vừa đủ.',
      chongchidinh: 'Tăng nhãn áp góc hẹp, dị ứng thành phần thuốc, trẻ dưới 2 tuổi.',
    },
  },

  // --- Vitamin & TPCN (58–62) ---
  58: {
    id: 58,
    name: 'Vitamin C 500mg',
    ingredient: 'Ascorbic Acid',
    desc: 'Viên uống bổ sung Vitamin C 500mg giúp tăng cường sức đề kháng, chống oxy hóa và hỗ trợ tổng hợp collagen.',
    price: 145000, originalPrice: 175000, discount: 17,
    rating: 4.7, ratingCount: 480,
    unit: '/hộp 100 viên', expiry: '06/2027',
    imgs: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Vitamin C',
    tabs: {
      congdung: {
        text: 'Vitamin C 500mg bổ sung Ascorbic Acid thiết yếu, tăng cường miễn dịch và chống oxy hóa.',
        list: ['Tăng cường hệ miễn dịch', 'Hỗ trợ tổng hợp collagen, làm đẹp da', 'Chống oxy hóa bảo vệ tế bào', 'Tăng hấp thu sắt'],
        warning: 'Không dùng quá 1000mg/ngày. Có thể gây tiêu chảy khi dùng liều cao.',
      },
      lieudung: 'Người lớn: 1–2 viên/ngày sau bữa ăn. Trẻ trên 12 tuổi: 1 viên/ngày.',
      thanhphan: 'Ascorbic Acid (Vitamin C) 500mg. Tá dược vừa đủ 1 viên.',
      chongchidinh: 'Sỏi thận oxalate, thalassemia, mẫn cảm Vitamin C.',
    },
  },
  59: {
    id: 59,
    name: 'Vitamin D3 2000IU',
    ingredient: 'Cholecalciferol',
    desc: 'Viên nang mềm Vitamin D3 2000IU bổ sung Cholecalciferol giúp xương chắc khỏe và tăng cường hệ miễn dịch.',
    price: 175000, originalPrice: 210000, discount: 17,
    rating: 4.7, ratingCount: 278,
    unit: '/hộp 60 viên', expiry: '11/2026',
    imgs: [
      'https://images.unsplash.com/photo-1612776572997-76cc42e058c3?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Vitamin D',
    tabs: {
      congdung: {
        text: 'Vitamin D3 2000IU cung cấp Cholecalciferol, hỗ trợ hấp thu canxi và tăng cường miễn dịch.',
        list: ['Tăng hấp thu Canxi và Phospho', 'Xương chắc khỏe, phòng loãng xương', 'Hỗ trợ hệ miễn dịch', 'Tốt cho sức khỏe tim mạch'],
        warning: 'Không dùng quá liều. Tham khảo bác sĩ nếu có bệnh thận hoặc tăng canxi máu.',
      },
      lieudung: 'Người lớn: 1 viên/ngày sau bữa ăn có chất béo.',
      thanhphan: 'Cholecalciferol (Vitamin D3) 2000IU (50mcg), dầu hướng dương, gelatin.',
      chongchidinh: 'Tăng canxi máu, tăng Vitamin D, sỏi thận, suy thận nặng.',
    },
  },
  60: {
    id: 60,
    name: 'Omega-3 Fish Oil',
    ingredient: 'EPA + DHA 1000mg',
    desc: 'Viên nang dầu cá Omega-3 hàm lượng cao với EPA và DHA giúp bảo vệ tim mạch và tăng cường trí nhớ.',
    price: 210000, originalPrice: 260000, discount: 19,
    rating: 4.6, ratingCount: 203,
    unit: '/hộp 60 viên', expiry: '08/2026',
    imgs: [
      'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Omega-3',
    tabs: {
      congdung: {
        text: 'Omega-3 Fish Oil 1000mg cung cấp EPA 300mg và DHA 200mg từ dầu cá tự nhiên.',
        list: ['Bảo vệ tim mạch, giảm triglyceride', 'Tăng cường trí nhớ và não bộ', 'Hỗ trợ sức khỏe mắt', 'Chống viêm, hỗ trợ xương khớp'],
        warning: 'Tham khảo bác sĩ nếu đang dùng thuốc chống đông máu. Không dùng khi dị ứng cá.',
      },
      lieudung: 'Người lớn: 1–2 viên/ngày trong bữa ăn.',
      thanhphan: 'Dầu cá 1000mg (EPA 300mg, DHA 200mg), Vitamin E, vỏ nang gelatin.',
      chongchidinh: 'Dị ứng hải sản, đang dùng Warfarin.',
    },
  },
  61: {
    id: 61,
    name: 'Canxi Nano MK7',
    ingredient: 'Calcium + Vitamin K2',
    desc: 'Viên uống bổ sung Canxi dạng Nano kết hợp Vitamin K2 (MK7) giúp canxi hấp thu tốt và đến đúng xương.',
    price: 290000, originalPrice: 350000, discount: 17,
    rating: 4.7, ratingCount: 315,
    unit: '/hộp 60 viên', expiry: '03/2027',
    imgs: [
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Vỉ', 'Viên'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Canxi',
    tabs: {
      congdung: {
        text: 'Canxi Nano MK7 kết hợp Canxi hạt Nano dễ hấp thu cùng Vitamin K2 MK7 dẫn canxi vào xương.',
        list: ['Hấp thu canxi hiệu quả hơn canxi thông thường', 'Vitamin K2 MK7 đưa canxi vào xương, không đọng mạch máu', 'Xương chắc khỏe, phòng loãng xương', 'Tốt cho răng và móng'],
        warning: 'Không dùng cùng thuốc chống đông máu nhóm Vitamin K. Uống cách xa bữa ăn giàu sắt.',
      },
      lieudung: 'Người lớn: 1–2 viên/ngày sau bữa ăn.',
      thanhphan: 'Canxi Nano 500mg, Vitamin K2 (MK7) 45mcg, Vitamin D3 400IU.',
      chongchidinh: 'Tăng canxi máu, sỏi thận canxi, đang dùng thuốc chống đông nhóm Warfarin.',
    },
  },
  62: {
    id: 62,
    name: 'Siro Fitobimbi Ferro',
    ingredient: 'Sắt hữu cơ + Vitamin C',
    desc: 'Siro bổ sung sắt hữu cơ cho trẻ em và phụ nữ mang thai. Sắt hữu cơ dễ hấp thu, ít gây táo bón hơn sắt vô cơ.',
    price: 168000, originalPrice: 200000, discount: 16,
    rating: 4.5, ratingCount: 267,
    unit: '/chai 200ml', expiry: '01/2027',
    imgs: [
      'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Vitamin & TPCN', catLink: 'search.html?cat=vitamin-tpcn', catSub: 'Sắt & Canxi',
    tabs: {
      congdung: {
        text: 'Siro Fitobimbi Ferro bổ sung sắt hữu cơ dễ hấp thu, phòng và điều trị thiếu máu thiếu sắt.',
        list: ['Bổ sung sắt hữu cơ dễ hấp thu', 'Vitamin C tăng hấp thu sắt', 'Phòng thiếu máu thiếu sắt', 'Phù hợp trẻ em và phụ nữ mang thai'],
        warning: 'Sắt có thể làm phân sẫm màu – đây là phản ứng bình thường. Tránh uống cùng sữa, trà, cà phê.',
      },
      lieudung: 'Trẻ 1–3 tuổi: 5ml/ngày. Trẻ 4–12 tuổi: 10ml/ngày. Người lớn: 15ml/ngày. Uống trước bữa ăn.',
      thanhphan: 'Sắt (III) hydroxide polymaltose 50mg/10ml, Vitamin C 30mg.',
      chongchidinh: 'Thừa sắt, thalassemia, dị ứng thành phần.',
    },
  },

  // --- Thiết bị y tế (63–66) ---
  63: {
    id: 63,
    name: 'Nhiệt kế điện tử',
    ingredient: 'Đo thân nhiệt chính xác',
    desc: 'Nhiệt kế điện tử kỹ thuật số cho kết quả nhanh và chính xác trong 60 giây, phù hợp cả trẻ em và người lớn.',
    price: 120000, originalPrice: 150000, discount: 20,
    rating: 4.6, ratingCount: 189,
    unit: '/cái', expiry: 'BH 12 tháng',
    imgs: [
      'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Sản phẩm', 'Hộp', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'Nhiệt kế',
    tabs: {
      congdung: {
        text: 'Nhiệt kế điện tử đo thân nhiệt nhanh chính xác, cảnh báo sốt bằng âm thanh.',
        list: ['Đo qua miệng, nách hoặc hậu môn', 'Kết quả sau 60 giây', 'Cảnh báo âm thanh khi trên 38°C', 'Lưu kết quả đo lần cuối'],
        warning: 'Vệ sinh đầu đo sau mỗi lần dùng. Không đo ngay sau ăn, uống hoặc vận động mạnh.',
      },
      lieudung: 'Đặt đầu đo vào nách hoặc miệng. Nhấn Start, giữ yên đến tiếng bíp.',
      thanhphan: 'Cảm biến nhiệt điện tử, màn hình LCD, pin LR41, bao đựng.',
      chongchidinh: 'Không dùng khi thiết bị bị hỏng, nứt vỡ. Không ngâm nước.',
    },
  },
  64: {
    id: 64,
    name: 'Máy đo huyết áp',
    ingredient: 'Tự động, cổ tay',
    desc: 'Máy đo huyết áp điện tử cổ tay tự động, hiển thị huyết áp tâm thu, tâm trương và nhịp tim. Phát hiện nhịp tim không đều.',
    price: 890000, originalPrice: 1100000, discount: 19,
    rating: 4.7, ratingCount: 421,
    unit: '/máy', expiry: 'BH 24 tháng',
    imgs: [
      'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Máy', 'Hộp', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'Huyết áp',
    tabs: {
      congdung: {
        text: 'Máy đo huyết áp cổ tay tự động, theo dõi huyết áp tại nhà tiện lợi và chính xác.',
        list: ['Đo huyết áp tâm thu, tâm trương và nhịp tim', 'Phát hiện nhịp tim không đều (arrhythmia)', 'Bộ nhớ 60 lần đo', 'Màn hình lớn dễ đọc'],
        warning: 'Nghỉ ngơi 5 phút trước khi đo. Không đo ngay sau vận động mạnh, ăn uống, hút thuốc.',
      },
      lieudung: 'Đeo vòng bít đúng vị trí cổ tay. Ngồi yên, nhấn Start. Đọc kết quả sau 30 giây.',
      thanhphan: 'Vòng bít cổ tay, màn hình LCD, pin AA x2 (kèm theo), hộp đựng.',
      chongchidinh: 'Không dùng khi vòng bít bị hỏng. Không thay thế chẩn đoán y tế chuyên nghiệp.',
    },
  },
  65: {
    id: 65,
    name: 'Băng gạc vô trùng',
    ingredient: 'Hộp 20 miếng',
    desc: 'Băng gạc y tế vô trùng dùng băng bó vết thương, thấm hút dịch tiết tốt, không dính vào vết thương.',
    price: 35000, originalPrice: 45000, discount: 22,
    rating: 4.4, ratingCount: 156,
    unit: '/hộp 20 miếng', expiry: '12/2027',
    imgs: [
      'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Miếng', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'Băng bó',
    tabs: {
      congdung: {
        text: 'Băng gạc vô trùng dùng sơ cứu, băng bó và che phủ vết thương hở.',
        list: ['Băng bó vết thương hở, vết cắt', 'Thấm hút dịch tiết tốt', 'Không dính vào vết thương', 'Vô trùng, an toàn cho mọi loại vết thương'],
        warning: 'Chỉ dùng 1 lần. Thay băng ít nhất 1 lần/ngày hoặc khi bị ướt, bẩn.',
      },
      lieudung: 'Rửa sạch vết thương. Đặt gạc lên vết thương và cố định bằng băng dính y tế.',
      thanhphan: 'Gạc bông vô trùng 100% cotton, kích thước 10x10cm.',
      chongchidinh: 'Không dùng lại băng gạc đã sử dụng.',
    },
  },
  66: {
    id: 66,
    name: 'Máy đo SpO2',
    ingredient: 'Đo nồng độ oxy máu',
    desc: 'Máy đo SpO2 kẹp ngón tay đo nồng độ oxy trong máu và nhịp tim nhanh chóng, chính xác. Tiện dụng theo dõi sức khỏe tại nhà.',
    price: 350000, originalPrice: 450000, discount: 22,
    rating: 4.6, ratingCount: 298,
    unit: '/máy', expiry: 'BH 12 tháng',
    imgs: [
      'https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Máy', 'Hộp', 'Chi tiết'],
    cat: 'Thiết bị y tế', catLink: 'search.html?cat=thiet-bi-y-te', catSub: 'SpO2',
    tabs: {
      congdung: {
        text: 'Máy đo SpO2 kẹp ngón tay đo nồng độ oxy máu (SpO2) và nhịp tim chỉ trong 10 giây.',
        list: ['Đo SpO2 (độ bão hòa oxy) chính xác', 'Đo nhịp tim đồng thời', 'Hiển thị sóng đập (plethysmograph)', 'Cảnh báo khi SpO2 dưới ngưỡng an toàn'],
        warning: 'Không dùng để chẩn đoán thay thế bác sĩ. SpO2 bình thường từ 95–100%.',
      },
      lieudung: 'Kẹp vào ngón trỏ, nhấn nút bật. Giữ yên khoảng 10 giây để đọc kết quả.',
      thanhphan: 'Cảm biến quang học, màn hình OLED, pin AAA x2 (kèm theo).',
      chongchidinh: 'Không dùng khi sơn móng tay đậm màu hoặc móng giả. Không thay thế thiết bị y tế chuyên nghiệp.',
    },
  },

  // --- Chăm sóc cá nhân (67–69) ---
  67: {
    id: 67,
    name: 'Kem dưỡng da',
    ingredient: 'Niacinamide + Hyaluronic Acid',
    desc: 'Kem dưỡng ẩm kết hợp Niacinamide 5% và Hyaluronic Acid 2%, dưỡng ẩm sâu và làm mờ vết thâm hiệu quả.',
    price: 320000, originalPrice: 400000, discount: 20,
    rating: 4.8, ratingCount: 425,
    unit: '/tuýp 50ml', expiry: '03/2027',
    imgs: [
      'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1631549916768-4119b4220dcd?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1612776572997-76cc42e058c3?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Sản phẩm', 'Texture', 'Thành phần'],
    cat: 'Chăm sóc cá nhân', catLink: 'search.html?cat=cham-soc-ca-nhan', catSub: 'Dưỡng da mặt',
    tabs: {
      congdung: {
        text: 'Kem dưỡng ẩm chuyên sâu Niacinamide 5% + Hyaluronic Acid 2% dưỡng ẩm và làm đều màu da.',
        list: ['Dưỡng ẩm sâu, giữ ẩm 24 giờ', 'Làm mờ vết thâm, đốm nâu', 'Cải thiện kết cấu da mịn màng', 'Phù hợp mọi loại da kể cả da nhạy cảm'],
        warning: 'Tránh vùng mắt. Ngừng dùng nếu kích ứng. Dùng kem chống nắng ban ngày.',
      },
      lieudung: 'Thoa đều lên mặt và cổ sau khi rửa sạch, sáng và tối.',
      thanhphan: 'Niacinamide 5%, Hyaluronic Acid 2%, Glycerin, Cetearyl Alcohol, nước tinh khiết.',
      chongchidinh: 'Da đang viêm nhiễm nặng. Test vùng nhỏ trước khi dùng toàn mặt.',
    },
  },
  68: {
    id: 68,
    name: 'Kem chống nắng SPF50',
    ingredient: 'Zinc Oxide + Titanium',
    desc: 'Kem chống nắng vật lý SPF50+ với Zinc Oxide và Titanium Dioxide, bảo vệ da khỏi UVA/UVB, thân thiện với da nhạy cảm.',
    price: 195000, originalPrice: 240000, discount: 19,
    rating: 4.6, ratingCount: 352,
    unit: '/tuýp 50ml', expiry: '08/2027',
    imgs: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1631549916768-4119b4220dcd?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Tuýp', 'Texture', 'Chi tiết'],
    cat: 'Chăm sóc cá nhân', catLink: 'search.html?cat=cham-soc-ca-nhan', catSub: 'Chống nắng',
    tabs: {
      congdung: {
        text: 'Kem chống nắng vật lý SPF50+ bảo vệ toàn diện khỏi tia UVA và UVB.',
        list: ['Bảo vệ da khỏi UVA/UVB hiệu quả', 'Chống nắng vật lý an toàn cho da nhạy cảm', 'Không gây bít lỗ chân lông', 'Kết cấu nhẹ, thấm nhanh'],
        warning: 'Thoa lại sau 2 giờ khi ở ngoài nắng. Tránh vùng mắt. Test vùng nhỏ trước khi dùng.',
      },
      lieudung: 'Thoa đều lên da mặt và vùng hở trước khi ra nắng 15–20 phút.',
      thanhphan: 'Zinc Oxide 10%, Titanium Dioxide 5%, Niacinamide 3%, nước tinh khiết, tá dược.',
      chongchidinh: 'Dị ứng Zinc Oxide hoặc Titanium Dioxide.',
    },
  },
  69: {
    id: 69,
    name: 'Gel rửa tay khô',
    ingredient: 'Cồn 70% kháng khuẩn',
    desc: 'Gel rửa tay khô cồn 70% diệt khuẩn nhanh không cần nước. Bổ sung Glycerin dưỡng ẩm giữ tay mềm mịn.',
    price: 48000, originalPrice: 60000, discount: 20,
    rating: 4.5, ratingCount: 334,
    unit: '/chai 100ml', expiry: '06/2026',
    imgs: [
      'https://images.unsplash.com/photo-1631549916768-4119b4220dcd?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Kết cấu', 'Nhãn'],
    cat: 'Chăm sóc cá nhân', catLink: 'search.html?cat=cham-soc-ca-nhan', catSub: 'Vệ sinh tay',
    tabs: {
      congdung: {
        text: 'Gel rửa tay khô Ethanol 70% tiêu diệt 99.9% vi khuẩn trong 30 giây.',
        list: ['Diệt 99.9% vi khuẩn, virus', 'Không cần nước, tiện lợi mọi lúc', 'Glycerin dưỡng ẩm tay mềm mịn', 'Khô nhanh, không dính tay'],
        warning: 'Tránh xa mắt và trẻ em. Không nuốt. Tránh xa nguồn lửa.',
      },
      lieudung: 'Bơm 2–3ml vào lòng tay. Xoa đều 30 giây đến khi khô.',
      thanhphan: 'Ethanol 70%, Glycerin, Carbomer, Triethanolamine, nước tinh khiết.',
      chongchidinh: 'Trẻ dưới 3 tuổi. Vết thương hở.',
    },
  },

  // --- Mẹ & Bé (70–72) ---
  70: {
    id: 70,
    name: 'Sữa bột Aptamil',
    ingredient: 'Dinh dưỡng trẻ 0–12 tháng',
    desc: 'Sữa bột Aptamil Stage 1 công thức gần giống sữa mẹ, bổ sung DHA, ARA và Prebiotics cho trẻ từ 0–12 tháng.',
    price: 580000, originalPrice: 650000, discount: 11,
    rating: 4.9, ratingCount: 567,
    unit: '/hộp 800g', expiry: '09/2026',
    imgs: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Nhãn', 'Chi tiết'],
    cat: 'Mẹ & Bé', catLink: 'search.html?cat=me-be', catSub: 'Sữa bột trẻ em',
    tabs: {
      congdung: {
        text: 'Aptamil Stage 1 cung cấp dinh dưỡng toàn diện cho trẻ 0–12 tháng.',
        list: ['DHA & ARA hỗ trợ não bộ và thị lực', 'Prebiotics GOS/FOS hỗ trợ tiêu hóa', 'Protein whey dễ tiêu hóa', 'Đầy đủ vitamin và khoáng chất'],
        warning: 'Sữa mẹ là tốt nhất. Chỉ dùng sữa công thức khi không thể cho bú.',
      },
      lieudung: 'Pha 1 muỗng gạt ngang (4.4g) với 30ml nước đun sôi để nguội.',
      thanhphan: 'Lactose, dầu thực vật, protein whey, DHA, ARA, GOS/FOS, Vitamin A, B, C, D, E, khoáng chất.',
      chongchidinh: 'Dị ứng protein sữa bò. Tham khảo bác sĩ trước khi dùng.',
    },
  },
  71: {
    id: 71,
    name: 'Siro ăn ngon B1+Lysine',
    ingredient: 'Vitamin B1 + Lysine',
    desc: 'Siro bổ sung Vitamin B1 và Lysine giúp kích thích ăn ngon, hỗ trợ tiêu hóa và tăng cường phát triển cho trẻ biếng ăn.',
    price: 125000, originalPrice: 150000, discount: 17,
    rating: 4.5, ratingCount: 298,
    unit: '/chai 100ml', expiry: '02/2027',
    imgs: [
      'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Mẹ & Bé', catLink: 'search.html?cat=me-be', catSub: 'Biếng ăn',
    tabs: {
      congdung: {
        text: 'Siro B1+Lysine kích thích vị giác, hỗ trợ tiêu hóa và tăng trưởng cho trẻ biếng ăn.',
        list: ['Kích thích ăn ngon, tăng cảm giác thèm ăn', 'Lysine hỗ trợ phát triển chiều cao', 'Vitamin B1 hỗ trợ hệ thần kinh và tiêu hóa', 'Phù hợp trẻ biếng ăn, chậm lớn'],
        warning: 'Uống trước bữa ăn 30 phút để đạt hiệu quả tốt nhất.',
      },
      lieudung: 'Trẻ 1–3 tuổi: 5ml x 2 lần/ngày. Trẻ 3–12 tuổi: 10ml x 2 lần/ngày.',
      thanhphan: 'Vitamin B1 10mg, L-Lysine HCl 250mg/10ml, Vitamin B6, tá dược siro.',
      chongchidinh: 'Dị ứng thành phần. Không thay thế bữa ăn chính.',
    },
  },
  72: {
    id: 72,
    name: 'Bột pha lắc DHA',
    ingredient: 'DHA + Vitamin tổng hợp',
    desc: 'Bột pha lắc bổ sung DHA và vitamin tổng hợp cho trẻ, dạng bột dễ pha, vị ngon trẻ dễ uống.',
    price: 210000, originalPrice: 260000, discount: 19,
    rating: 4.6, ratingCount: 187,
    unit: '/hộp 30 gói', expiry: '05/2027',
    imgs: [
      'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Hộp', 'Gói', 'Chi tiết'],
    cat: 'Mẹ & Bé', catLink: 'search.html?cat=me-be', catSub: 'DHA & Não bộ',
    tabs: {
      congdung: {
        text: 'Bột pha lắc DHA bổ sung axit béo DHA và đa vitamin hỗ trợ phát triển trí não cho trẻ.',
        list: ['DHA hỗ trợ phát triển não bộ và thị lực', 'Bổ sung đa vitamin thiết yếu', 'Dạng bột dễ pha, vị ngon trẻ thích', 'Phù hợp trẻ từ 1 tuổi trở lên'],
        warning: 'Không thay thế sữa mẹ hoặc sữa công thức cho trẻ dưới 1 tuổi.',
      },
      lieudung: 'Pha 1 gói với 150ml nước hoặc sữa ấm. Cho trẻ uống 1 gói/ngày.',
      thanhphan: 'DHA 100mg, Vitamin A, C, D, E, B complex, Canxi, Kẽm/gói.',
      chongchidinh: 'Dị ứng hải sản (DHA từ cá). Trẻ dưới 1 tuổi.',
    },
  },

  // --- Thuốc xịt mũi (73–75) ---
  73: {
    id: 73,
    name: 'Otrivin 0.1%',
    ingredient: 'Xylometazoline HCl',
    desc: 'Thuốc xịt mũi Otrivin 0.1% thông mũi nhanh chóng, hiệu quả trong 10 phút, duy trì tới 10 giờ.',
    price: 72000, originalPrice: 90000, discount: 20,
    rating: 4.5, ratingCount: 312,
    unit: '/chai 10ml', expiry: '07/2026',
    imgs: [
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc xịt mũi', catLink: 'search.html?cat=thuoc-xit-mui', catSub: 'Thông mũi',
    tabs: {
      congdung: {
        text: 'Otrivin 0.1% chứa Xylometazoline làm co mạch niêm mạc mũi, thông mũi nhanh và kéo dài.',
        list: ['Thông mũi nhanh trong 10 phút', 'Hiệu quả duy trì tới 10 giờ', 'Giảm nghẹt mũi do cảm, viêm xoang, dị ứng', 'Dễ xịt, tiện dùng'],
        warning: 'Không dùng quá 3 ngày liên tục. Dùng kéo dài có thể gây phụ thuộc thuốc (rebound effect).',
      },
      lieudung: 'Người lớn: xịt 1–2 nhát mỗi bên mũi, tối đa 3 lần/ngày. Không dùng cho trẻ dưới 6 tuổi.',
      thanhphan: 'Xylometazoline HCl 0.1%, Natri Clorid, tá dược vừa đủ.',
      chongchidinh: 'Viêm mũi teo, tăng nhãn áp, cao huyết áp nặng, trẻ dưới 6 tuổi, phụ nữ mang thai.',
    },
  },
  74: {
    id: 74,
    name: 'Nasonex Spray',
    ingredient: 'Mometasone Furoate',
    desc: 'Xịt mũi corticosteroid Nasonex chứa Mometasone Furoate, điều trị viêm mũi dị ứng và polyp mũi hiệu quả.',
    price: 185000, originalPrice: 220000, discount: 16,
    rating: 4.7, ratingCount: 278,
    unit: '/chai 140 liều', expiry: '10/2026',
    imgs: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc xịt mũi', catLink: 'search.html?cat=thuoc-xit-mui', catSub: 'Dị ứng mũi',
    tabs: {
      congdung: {
        text: 'Nasonex chứa Mometasone Furoate là corticosteroid xịt mũi tại chỗ, kháng viêm và kháng dị ứng.',
        list: ['Điều trị viêm mũi dị ứng theo mùa và quanh năm', 'Giảm hắt hơi, sổ mũi, nghẹt mũi do dị ứng', 'Điều trị polyp mũi', 'Hiệu quả cao, ít tác dụng toàn thân'],
        warning: 'Cần 2–4 ngày để thấy hiệu quả đầy đủ. Cần dùng đều đặn mỗi ngày để đạt hiệu quả tối ưu.',
      },
      lieudung: 'Người lớn và trẻ trên 12 tuổi: 2 nhát mỗi bên mũi, 1 lần/ngày (buổi sáng).',
      thanhphan: 'Mometasone Furoate 50mcg/nhát xịt, tá dược vừa đủ.',
      chongchidinh: 'Nhiễm khuẩn mũi xoang đang cấp tính chưa điều trị, dị ứng Mometasone, trẻ dưới 2 tuổi.',
    },
  },
  75: {
    id: 75,
    name: 'Sterimar Baby',
    ingredient: 'Nước muối sinh lý',
    desc: 'Xịt mũi nước muối sinh lý đẳng trương Sterimar Baby, nhẹ nhàng vệ sinh mũi cho trẻ sơ sinh và trẻ nhỏ.',
    price: 95000, originalPrice: 115000, discount: 17,
    rating: 4.8, ratingCount: 445,
    unit: '/chai 100ml', expiry: '12/2027',
    imgs: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop',
    ],
    thumbLabels: ['Chai', 'Hộp', 'Chi tiết'],
    cat: 'Thuốc xịt mũi', catLink: 'search.html?cat=thuoc-xit-mui', catSub: 'Vệ sinh mũi',
    tabs: {
      congdung: {
        text: 'Sterimar Baby nước muối sinh lý đẳng trương vệ sinh mũi nhẹ nhàng, an toàn cho trẻ sơ sinh.',
        list: ['Vệ sinh mũi hằng ngày cho trẻ sơ sinh', 'Làm loãng và tống dịch nhầy mũi', 'Giảm nghẹt mũi nhẹ không dùng thuốc', 'An toàn 100%, không gây kích ứng'],
        warning: 'Dùng được hằng ngày không giới hạn số lần. Không dùng chung giữa các trẻ.',
      },
      lieudung: 'Trẻ sơ sinh: xịt 1–2 nhát mỗi bên mũi, 2–6 lần/ngày hoặc khi cần.',
      thanhphan: 'Natri Clorid 0.9% (nước muối đẳng trương), nước tinh khiết vô trùng.',
      chongchidinh: 'Không có chống chỉ định đặc biệt. Tham khảo bác sĩ nếu trẻ có bệnh lý mũi họng.',
    },
  },
};